import Head from "next/head";
import { Htag } from "../components/Htag/Htag";
import { Button } from "../components/Button/Button";


export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Htag tag="h2">Hell</Htag>
     <Button className="asdasd" appearance="primary">Primary</Button>
     <Button appearance="ghost">Ghost</Button>
    </>
  );
}
